version: '2'
services:
    app:
        image: django
        ports:
            - 8000:8000
        volumes:
            - ./:/app
    mysql:
        image: mysql:5.7
        volumes:
            - ./datos:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=mysql

